### ISSUE TITLE
Python v2.5 wheel does not appear to actually be v2.5 of tflite

### ISSUE THREAD

**Issue by gkoundry** [google-coral/py-repo#4]
If I install tflite via `pip3 install --index-url https://google-coral.github.io/py-repo/ tflite_runtime` it installs v2.5 of tflite_runtime.  However, it apparently lacks the method `Interpreter.get_signature_runner()` which I'm pretty sure should be available in 2.5.

**Comment by hjonnala** [comment]
Hi, please let us know

1. python version
2. operating system

please try to install tflite_runtime from these wheels: https://github.com/google-coral/pycoral/releases

**Comment by gkoundry** [comment]
I'm using Python 3.8 on Ubuntu 18.04.  I've already tried manually downloading `tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl
` and it has the same issue.

**Comment by dmitriykovalev** [comment]
We'd released slightly earlier than the TF 2.5 was finalized, there is some discrepancy here. We are on the way of releasing updated wheels (current [TF 2.5.0](https://github.com/tensorflow/tensorflow/tree/v2.5.0) tag) which should contain `Interpreter.get_signature_runner()`.

**Comment by gkoundry** [comment]
Thank you.

**Comment by hjonnala** [comment]
@ gkoundry the issue has been fixed with new tflite releases. Please install from these wheels: https://github.com/google-coral/pycoral/releases

Thanks

**Comment by hjonnala** [comment]
![image](https://user-images.githubusercontent.com/86132058/127346086-d1d98c8b-8f63-40e7-890d-dec5c247190d.png)
